#pragma once

#include "sdkconfig.h"
#include "esp_wifi_types.h"

#define ANCHOR_ID          CONFIG_ANCHOR_ID
#define ANCHOR_CHANNEL     CONFIG_ANCHOR_WIFI_CHANNEL
#define ANCHOR_UART_BAUD   CONFIG_ANCHOR_UART_BAUD
#define ANCHOR_QUEUE_DEPTH CONFIG_ANCHOR_QUEUE_DEPTH
#define ANCHOR_STATS_MS    (CONFIG_ANCHOR_STATS_INTERVAL_S * 1000)

#if CONFIG_ANCHOR_FILTER_MGMT_ONLY
#define ANCHOR_PROMISC_FILTER (WIFI_PROMIS_FILTER_MASK_MGMT)
#elif CONFIG_ANCHOR_FILTER_ALL
#define ANCHOR_PROMISC_FILTER (WIFI_PROMIS_FILTER_MASK_ALL)
#else /* MGMT + DATA (default) */
#define ANCHOR_PROMISC_FILTER (WIFI_PROMIS_FILTER_MASK_MGMT | WIFI_PROMIS_FILTER_MASK_DATA)
#endif

#ifdef CONFIG_ANCHOR_CSI_OUTPUT_RAW_IQ
#define ANCHOR_OUTPUT_RAW_IQ 1
#else
#define ANCHOR_OUTPUT_RAW_IQ 0
#endif

#ifdef CONFIG_ANCHOR_UDP_ENABLE
#define ANCHOR_UDP_ENABLE   1
#define ANCHOR_UDP_SSID     CONFIG_ANCHOR_UDP_SSID
#define ANCHOR_UDP_PASSWORD CONFIG_ANCHOR_UDP_PASSWORD
#define ANCHOR_UDP_GW_IP    CONFIG_ANCHOR_UDP_GATEWAY_IP
#define ANCHOR_UDP_GW_PORT  CONFIG_ANCHOR_UDP_GATEWAY_PORT
#else
#define ANCHOR_UDP_ENABLE   0
#endif
